[deps]
HOHQMesh = "e4f4c7b8-17cb-445a-93c5-f69190ed6c8c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEqLowStorageRK = "b0944070-b475-4768-8dec-fb6eb410534d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"
Trixi2Vtk = "bc1476a1-1ca6-4cc3-950b-c312b255ff95"
TrixiBase = "9a0f1c46-06d5-4909-a5a3-ce25d3fa3284"
TrixiShallowWater = "804cb1fc-5b08-4398-a671-a789bfe091b3"

[compat]
LinearAlgebra = "1"
OrdinaryDiffEqLowStorageRK = "1.3"
Plots = "1.9"
Trixi = "0.12"
Trixi2Vtk = "0.3.23"
TrixiBase = "0.1.1"
TrixiShallowWater = "0.2"
